
function [ back_focal_length, effective_focal_length ] = get_focal_length( ...
    name, pd, ml, nrays, max_deg, max_time, anat_boundary, anat_average, ...
    functional_specified, functional_unspecified, alpha, ...
    optimizer, solver, ...
    varargin )

    % get the eye that satisfies our input parameters
    eye_map = EyeDatabase( );
    eye_entry = eye_map.GetReconstructed( ...
        name, pd, ml, nrays, max_deg, max_time, ...
        anat_boundary, anat_average, ...
        functional_specified, functional_unspecified, alpha, ...
        optimizer, solver );
    
    % return the focal length
    [ back_focal_length, effective_focal_length ] = eye_entry.eye.BackFocalLength( 4, 50, 10, [ 0.01, 40.0 ], false );
end